import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import { Providers } from "./Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Suspense fallback="Loading...">{children}</Suspense>
        </Providers>
      </body>
    </html>
  );
}
